# Generated by Django 5.1.1 on 2024-10-01 16:29

import menu.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drink_name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to=menu.models.Upload)),
                ('size', models.CharField(choices=[('S', 'S'), ('L', 'L')], max_length=10)),
                ('price_s', models.IntegerField(default=0)),
                ('price_l', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Menu',
                'verbose_name_plural': 'Menus',
            },
        ),
    ]
