# Generated by Django 5.1.1 on 2024-10-01 17:21

import menu.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu_iced',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drink_name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to=menu.models.Upload)),
                ('price_s', models.IntegerField(default=0)),
                ('price_l', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Menu_iced',
                'verbose_name_plural': 'Menus_iced',
            },
        ),
        migrations.RemoveField(
            model_name='menu',
            name='size',
        ),
    ]
